### PR TITLE
Fix: Postgres error on runworker

### PR DESCRIPTION
**Pull request by Lapinator**
This PR fix runworker error for Postgresql

	Job Finished.
	---------------------------------------------------------------
	[2019-09-08 23:43:12] Looking for Job ...
	Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  function unix_timestamp() does not exist
	LINE 1: ...d < $3 OR (fetched) IS NULL)) AND failed < $4 AND UNIX_TIMES...
                                                             ^

### CODE REVIEW

**Comment by dereuromark** [comment]
Are there other similar cases not covered by tests yet?

**Comment by Lapinator** [comment]
Not to my knowledge, I just made a report originally to fix a bug that I had with its solution

**Comment by dereuromark** [comment]
But does that mean that we dont have a unit test for postgres and requestJob() method?
As Travis should have shown this error too, right?

**Comment by dereuromark** [comment]
Ah, they are only checked for MySQL:

    $this->skipIf(strpos($config['driver'], 'Mysql') === false, 'Only Mysql is working yet for this.');

We should probably include Postgres here

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-queue/pull/242

**Pull request merged**
