### PR TITLE
Run tests also for Postgres.

### PR DESCRIPTION
**Pull request by dereuromark**
Enable tests for postgres

Refs https://github.com/dereuromark/cakephp-queue/pull/241

### CODE REVIEW

**Comment by dereuromark** [comment]
@Lapinator
https://travis-ci.org/dereuromark/cakephp-queue/jobs/582576443 shows the remaining fail

Is that sth you encounter in production too? A different order than expected?

**Comment by Lapinator** [comment]
I reproduced the bug at home, I will fix tonight, I suspect the inner workings of postgres that differs from those of mysql

**Comment by Lapinator** [comment]
I have found :

	git diff src/Model/Table/QueuedJobsTable.php
	diff --git a/src/Model/Table/QueuedJobsTable.php b/src/Model/Table/QueuedJobsTable.php
	index 8b5c7ee..29e0e47 100644
	--- a/src/Model/Table/QueuedJobsTable.php
	+++ b/src/Model/Table/QueuedJobsTable.php
	@@ -370,7 +370,7 @@ class QueuedJobsTable extends Table {
	                                break;
	                        case static::DRIVER_POSTGRES:
	                                $age = $query->newExpr()
	-                                       ->add('COALESCE((EXTRACT(EPOCH FROM now()) - EXTRACT(EPOCH FROM notbefore)), 0)');
	+                                       ->add('COALESCE(EXTRACT(EPOCH FROM notbefore) - (EXTRACT(EPOCH FROM now())), 0)');
	                                break;
	                }
	                $options = [

**Comment by dereuromark** [comment]
Are you sure? At least locally this doesnt seem to fix the issue.

**Comment by Lapinator** [comment]
At home that has well fixed the concerns. when I did the tests I had the values upside down. do you have the new line well or I have to reverse the 2 elements ?

->add('COALESCE(EXTRACT(EPOCH FROM notbefore) - (EXTRACT(EPOCH FROM now())), 0)');

**Pull request merged**
