### PR TITLE
fix deprecation

### PR DESCRIPTION
**Pull request by LordSimal**
Found another small deprecation.
Don't know why this Trait was in there in the first place to be honest...

### CODE REVIEW

**Comment by LordSimal** [comment]
All of these are related to the fact, that the `ProcessEndingException` doesn't correctly extend from `\Cake\Core\Exception\Exception` for some reaon.

Even more strange is the fact, that locally I have no phpstan errors.

**Comment by LordSimal** [comment]
I had an old version of phpstan, that was the reason. Let me check whats going on here

**Comment by LordSimal** [comment]
See https://github.com/dereuromark/cakephp-queue/pull/332

**Comment by dereuromark** [comment]
Some changes break for us now

> Failure Message: Error: Call to a member function get() on null #0 /disk2/2022-06-02_11-47/vendor/dereuromark/cakephp-queue/src/Queue/Processor.php(202):

**Comment by LordSimal** [comment]
I can't see a `->get()` call on line 202 currently in the master branch.
The only `->get()` call happens in the constructor on the tableLocator.

**Comment by dereuromark** [comment]
Weird, I was trying master instead of latest tag and it failed.

**Comment by LordSimal** [comment]
Latest tag hasn't the deprecation changes in there anyways
https://github.com/dereuromark/cakephp-queue/compare/6.3.2...master

**Comment by dereuromark** [comment]
Exactly my point :) See my last message/sentence.

**Comment by LordSimal** [comment]
I am running current dev-master as well on my app for at least a couple of weeks without having any problems till now.
So can you provide more info on how to reproduce that problem?

**Comment by dereuromark** [comment]
Ah, thats the BC break:
https://github.com/dereuromark/cakephp-queue/compare/6.3.2...master#diff-105f867b1d032b60bf14fc4d2ff4bf5502ce80783caad3484c0fb7c717a03a35R22

You cannot just remove this in a minor even as the extended classes are using that trait.

**Comment by dereuromark** [comment]
Stack trace reporting is just confused about the stack level (wrong output of stack, therefore wrong class and line)

**Comment by LordSimal** [comment]
Well to be fair, I just fixed the deprecation warnings.
On which version they are released is not on me, thats how you decide to tag those changes.

**Comment by dereuromark** [comment]
Well, I assumed any deprecation fix would be a patch release at the most, maybe a minor.
I would never have merged with the intend of major.

**Comment by LordSimal** [comment]
I thought this was clear when I clarified the change for the `->fetchTable()` method in https://github.com/dereuromark/cakephp-queue/pull/326

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/commit/31d48926128a089170a8c60d4ce77ae7640c8103

**Comment by LordSimal** [comment]
So should we add a test which checks for the old ModelAwareTrait functionality in a task?

**Comment by dereuromark** [comment]
We could

**Pull request merged**
