### PR TITLE
Alter Table Column failure_message field from type text to mediumtext via migration

### LINKED ISSUE #146: Use LONGTEXT for failure_message
I am storing quite big error messages inside possibly a few hundred KB of utf8 CSS.
Would it hurt to change the column type from TEXT to ~~LONGTEXT~~ MEDIUMTEXT?

Edit: Or MEDIUMTEXT for that matter.
https://mariadb.com/kb/en/library/text/
https://mariadb.com/kb/en/library/mediumtext/
https://mariadb.com/kb/en/library/longtext/

### PR DESCRIPTION
**Pull request by inoas**
Fixes #146

### CODE REVIEW

**Comment by inoas** [comment]
p.s.: I can confirm that these work for MariaDB 10.2 btw.

**Comment by dereuromark** [comment]
Is it really necessary to make this that large?
I mean couldnt this be stored in the existing one?

**Comment by inoas** [comment]
The failure? It is related to the job running and is the pure failure message. Making it mediumtext is really not a problem at all IMHO 16mb max. Versus the longtext being 4GB or so...

I mean, you can still reject it - but then people *may* have truncated error logs for no (sane) reason, IMHO.

**Comment by inoas** [comment]
When I run phpunit I get a lot of 
```
PDOException: SQLSTATE[HY000]: General error: 1 near "FOR": syntax error
...
PDOException: SQLSTATE[HY000]: General error: 1 no such function: UNIX_TIMESTAMP
```

Taking a look at the fixtures it seems that they are insensitive to charsets and collations.
```php
public $fields = [
	'id' => ['type' => 'integer'],
	'job_type' => ['type' => 'string', 'length' => 45, 'null' => false, 'default' => null],
	'data' => ['type' => 'text', 'null' => true, 'default' => null],
	'priority' => ['type' => 'integer', 'length' => 3, 'null' => false, 'default' => 5],
	'job_group' => ['type' => 'string', 'length' => 255, 'null' => true],
	'reference' => ['type' => 'string', 'length' => 255, 'null' => true],
	'created' => ['type' => 'datetime', 'null' => true],
	'notbefore' => ['type' => 'datetime', 'null' => true],
	'fetched' => ['type' => 'datetime', 'null' => true],
	'completed' => ['type' => 'datetime', 'null' => true],
	'progress' => ['type' => 'float', 'null' => true],
	'status' => ['type' => 'string', 'length' => 255, 'null' => true, 'default' => null],
	'failed' => ['type' => 'integer', 'length' => 3, 'null' => false, 'default' => 0],
	'failure_message' => ['type' => 'text', 'null' => true, 'default' => null],
	'workerkey' => ['type' => 'string', 'length' => 45, 'null' => true, 'default' => null],
	'_constraints' => [
		'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
	],
];

public $fields = [
	'id' => ['type' => 'integer', 'length' => 11, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
	'pid' => ['type' => 'string', 'length' => 30, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
	'created' => ['type' => 'datetime', 'length' => null, 'null' => true, 'default' => null, 'comment' => '', 'precision' => null],
	'modified' => ['type' => 'datetime', 'length' => null, 'null' => true, 'default' => null, 'comment' => '', 'precision' => null],
	'_constraints' => [
		'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
	],
];
```

...they also declare string length... which makes me wonder why the fields in the database are text rather than varchar.

**Comment by dereuromark** [comment]
What DB type did you run? mysql?

**Comment by inoas** [comment]
MariaDB 10.2

**Pull request merged**
