### PR TITLE
Prepare for a plugin 4.0 major release

### PR DESCRIPTION
**Pull request by dereuromark**
What do people think?

Improvements:
- Use interface contract now (for method run)
- All jobs run() void, throw exceptions for failing

Discussion needed:

- PHP 7.1 return type void on interface to avoid accidental return bool? More strictness for less mistakes.

=> PHP7.1/PHP7.2+ then for 4.0

I am thinking:

- 4.0 for Cake3 with cleanup (remove file pid and deprecations), add interface contracting, void tasks, but still PHP5.6?
- 5.0 as simple Cake4 upgrade then, almost 0-changes necessary apart from typehinting, PHP7.1+

### CODE REVIEW

**Comment by dereuromark** [comment]
Its written above.

**Comment by challgren** [comment]
> Its written above.

But in composer.json

**Comment by dereuromark** [comment]
I wasnt sure if I should release a major first for 3.x and then upgrade to 4.x as another major.
To ease migration... Not sure.

**Comment by dereuromark** [comment]
Things left:

- [ ] Use interface for add() method, to make it easier to decide if such a method is available.

**Comment by dereuromark** [comment]
This is now ready to be released as 4.0
Any last QA here from people using this plugin?

**Pull request merged**
