### PR TITLE
Updated clearDoublettes method to use Cake queries

### PR DESCRIPTION
**Pull request by biggins**

### CODE REVIEW

**Comment by dereuromark** [comment]
Nice :)

**Comment by biggins** [comment]
Would it be possible to get this merged?

**Comment by dereuromark** [comment]
Do we need tests for this?

**Comment by dereuromark** [comment]
Maybe someone has time to add some tests later on?

**Comment by biggins** [comment]
Thank you for merging, I will try to get some written in the upcoming weeks

**Pull request merged**
