### PR TITLE
Expose kill signal parameter from terminateProcess() in delete() 

### PR DESCRIPTION
**Pull request by umer936**
I need to use a SIGKILL instead of a SIGTERM for terminating a job. This allows that functionality without having to modify the vendor package

### CODE REVIEW

**Comment by dereuromark** [comment]
builds are red

**Comment by umer936** [comment]
Maybe my brain isn't working lol but what am I missing? Why does the failure say the type needs to be int rather than int|null ? 
Shouldn't $arg in terminate() default to SIGTERM if null is passed in?

**Comment by dereuromark** [comment]
No, not if you pass a parameter

**Comment by dereuromark** [comment]
Any update on this?

**Comment by umer936** [comment]
I had wanted to avoid duplicating the default of SIGTERM, but seems like I had to. 

Do you want me to close this one and do it as a new PR?

**Comment by dereuromark** [comment]
No seems fine

**Comment by dereuromark** [comment]
Added via https://github.com/dereuromark/cakephp-queue/commit/9670cfa624c954e3565da6353910df9e85ab9265 to avoid stringish values to go into the function which expects int.

**Pull request closed without merging**
